string(ASCII 27 Esc)
set(ColourReset "${Esc}[m")
set(ColourBold "${Esc}[1m")
set(Red "${Esc}[31m")
set(Green "${Esc}[32m")
set(Yellow "${Esc}[33m")
set(Blue "${Esc}[34m")
set(Magenta "${Esc}[35m")
set(Cyan "${Esc}[36m")
set(White "${Esc}[37m")
set(BoldRed "${Esc}[1;31m")
set(BoldGreen "${Esc}[1;32m")
set(BoldYellow "${Esc}[1;33m")
set(BoldBlue "${Esc}[1;34m")
set(BoldMagenta "${Esc}[1;35m")
set(BoldCyan "${Esc}[1;36m")
set(BoldWhite "${Esc}[1;37m")

function(ERROR_LOG msg)
  message(FATAL_ERROR "${Red}[ERROR] ${msg}${ColourReset}")
endfunction()

function(WARNING_LOG msg)
  message(WARNING "${Blue}[WARNING] ${msg}${ColourReset}")
endfunction()

function(INFO_LOG msg)
  message(STATUS "${Green}[INFO] ${msg}${ColourReset}")
endfunction()


